metadata <- golem::get_golem_options("metadata")
of_interest <- golem::get_golem_options("of_interest")
# #meta_sum <- get_condition_summary(metadata)
# samples <- get_all_sample_names(metadata)
measure_names <- rownames(golem::get_golem_options("dataset"))
sample_names <- golem::get_golem_options("sample_names")
